export const GOOGLE_CLIENT_ID =
  "99437757855-jp46msh793i8jf96s9gm6f87fb2uue51.apps.googleusercontent.com";
export const ROOT_FOLDER_ID = "1IkKd6_bh0ybriKUfkyagnyjT9mBGexiR";
export const SYSTEM_2025_FOLDER_ID = "11x-VqaBdYVWczCGGXtNYTkUOEdd6Qkin";
export const ALLOWED_DOMAIN = "institutoirina.com";

export const CET_CATEGORIES = [
  "EVALUACION ACTUAL",
  "PROYECTOS DE SALAS",
  "INFORMES CUATRIMESTRALES",
  "INFORMES FINALES",
  "INFORMES MENSUALES",
  "PLAN DE TRATAMIENTO",
  "PLANIFICACIONES ANUALES",
  "PLANIFICACIONES TRIMESTRALES",
  "PROTOCOLOS DE RUTINAS Y CRISIS",
] as const;

export const INCLUSION_LEVELS = [
  "NIVEL INICIAL",
  "NIVEL PRIMARIO",
  "NIVEL SECUNDARIO",
] as const;

export const INCLUSION_CATEGORIES = [
  "INFORME FINAL",
  "INFORMES MENSUALES",
  "INFORMES SEMESTRALES",
  "INFORMES TRIMESTRALES",
  "OBJETIVOS",
  "PLAN DE TRATAMIENTO",
  "PLANIFICACIONES",
  "PPI 2026",
] as const;